---
deployment:
      tasks:
        - export DEPLOYPATH=/home/jameselk/sites/nswpropertysalesdata.com-ops/pythonapp
        - /bin/cp /home/jameselk/sites/nswpropertysalesdata.com-ops/nsw-property-sales-data-cleaner/1-download.py $DEPLOYPATH
        - /bin/cp /home/jameselk/sites/nswpropertysalesdata.com-ops/nsw-property-sales-data-cleaner/2-extract.py $DEPLOYPATH
        - /bin/cp /home/jameselk/sites/nswpropertysalesdata.com-ops/nsw-property-sales-data-cleaner/3-archive.py $DEPLOYPATH
